# Generated by Django 4.1.7 on 2023-03-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.me')),
            ],
        ),
    ]
