# Generated by Django 4.1.7 on 2023-03-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('tools', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.TextField()),
                ('photo', models.ImageField(upload_to='projects')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.me')),
            ],
        ),
    ]
