# Generated by Django 4.1.7 on 2023-04-08 17:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
